### PR TITLE
windows build config

### PR DESCRIPTION
**Pull request by jgarnierGit**
Hi!

First I'd like to say that I'm really glad to find out your repo and to see you are actively working on it :D 
That's so cool !

I bring you this contribution to build your repo on windows CMD environment
I removed the part related to the user rights as Windows has its own personal way to deal with that,

Also I was not confident with your workflow of launching build.sh, then run the serve-dir alias ? 
I found out it may be redundant, at least I get the expected result by running the command I've documented in the README,md
Feel free to tell me more about it !

Cheers,
Jonathan

### CODE REVIEW

**Comment by evoyy** [comment]
Thanks. I still haven't managed to get it fully working. See this comment for details: https://github.com/projectM-visualizer/projectm/issues/812#issuecomment-2163832118

I have a few things to try:

- experiment with WebGL context atrributes
https://emscripten.org/docs/api_reference/html5.h.html#c.EmscriptenWebGLContextAttributes

- experiment with emscripten build settings
https://github.com/emscripten-core/emscripten/blob/main/src/settings.js

**Comment by evoyy** [comment]
Also, I clarified the serve-dir alias in the readme. It was a bit confusing. It's only needed if you don't have python installed locally (like me).

**Comment by jgarnierGit** [comment]
I will stay up-to-date on your work, you saved me a lot of time and pain!

FYI, I used it on a personal project https://github.com/jgarnierGit/web-music-library ;)

**Comment by evoyy** [comment]
Glad to hear it helped. It was admittedly a pain to get projectM working. At least it's kind of working now. The only things to fix now are to work out why there is a 5-7 seconds delay when loading presets, and the transitions/blend feature cause it to freeze when changing presets, so that feature is disabled. Hopefully the projectM maintainers can help look into this.

**Pull request merged**
